apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-0
  namespace: raylab
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi