apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: raylab
  labels:
    service: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    #protocol: TCP
    targetPort: 80
    nodePort: 30078
  selector:
    service: nginx
