apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: lens-metrics
  labels:
     name: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    name: web
    #protocol: TCP
    targetPort: 9090
    nodePort: 30025
  selector:
    name: prometheus
