apiVersion: v1
kind: Service
metadata:
  name: pushgateway-svc
  namespace: rayprometheus
  labels:
     app: pushgateway
spec:
  type: ClusterIP
  ports:
  - port: 9091
    name: web
    protocol: TCP
    targetPort: 9091
  selector:
    app: pushgateway
